language : java
script : 
  - mvn clean verify
  - docker build -t marceau/changelog ./sample-application-db-changelog-job
  - docker build -t marceau/httpserver ./sample-application-http-api-server
  - docker login -u $USR_DOCKR -p $PWD_DOCKR
  - docker push marceauguy/changelog:marceau/changelog
  - docker push marceauguy/httpserver:marceau/httpserver