language : java
script : 
  - mvn clean verify
  - docker build -t marceauguy/changelog ./sample-application-db-changelog-job
  - docker build -t marceauguy/httpserver ./sample-application-http-api-server
  - docker login -u $USR_DOCKR -p $PWD_DOCKR
  - docker push marceauguy/changelog
  - docker push marceauguy/httpserver